name: gift_of_the_nile
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^1.5.6
  floating_search_bar: ^0.2.0
  flutter_icons: ^0.3.1
  rxdart: ^0.22.0
  circle_list: ^1.0.0
  auto_size_text: ^2.1.0
  google_maps_flutter: ^0.5.21+6
  geolocator: ^5.1.3
  flutter_staggered_animations: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0
  cached_network_image: ^1.1.1
  peek_and_pop: ^1.0.2
  url_launcher: ^5.1.4
  timeline_list: ^0.0.5
  koukicons: ^2.0.1
  shared_preferences: ^0.5.3+4
  http: ^0.12.0+2
  flutter_rating_bar: ^3.0.0
  flutter_swiper: ^1.1.6
  dio: ^3.0.3
  dio_http_cache: ^0.2.0
  marquee: ^1.3.1
  flutter_html: ^0.11.0
  path_provider: ^1.3.0
  flutter_downloader: ^1.2.2
  path: ^1.6.4
  flutter_full_pdf_viewer: ^1.0.6
  esys_flutter_share: ^1.0.2




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - resources/animation/
    - resources/images/
    - resources/data/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Righteous
      fonts:
        - asset: fonts/Righteous-Regular.ttf

    - family: Egyptian
      fonts:
        - asset: fonts/AncientEgyptianHieroglyphs.otf

